# -*- coding: utf-8 -*-
"""Preprosesing_QueryTes_Fix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QYoIyR-EexexQ3EoN8sFYVxhYCN7RgTc
"""

pip install sastrawi

#from bs4 import BeautifulSoup
#import urllib.request
import string
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from tqdm import tqdm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
from IPython.display import display, clear_output
import ipywidgets as widgets

# Load file kompas
paper_x = pd.read_excel('/content/sample_data/hasil_scraping_kompas.xlsx')

# Kolom: 0=URL, 1=Judul, 2=Waktu, 3=Content
paper = paper_x.values.tolist()

print(f"Total data berita: {len(paper)}")

# Preprocessing korpus berita

factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()
stemmer = StemmerFactory().create_stemmer()
processed_paper = []
words = []

for x in tqdm(paper, desc='Processing Berita', unit='berita'):
    # x[1] adalah Judul, x[3] adalah Content
    text_gabungan = str(x[1]) + " " + str(x[3])

    text = text_gabungan.lower()
    remove_punctuation_map = dict((ord(char), None) for char in string.punctuation)
    text = text.translate(remove_punctuation_map)
    text = stopword.remove(text)

    tokens = text.split()
    stemmed_tokens = [stemmer.stem(t) for t in tokens]

    processed_paper.append(' '.join(stemmed_tokens))
    words += list(set(stemmed_tokens))

print("Preprocessing selesai.")

print("Menyimpan data ke corpus/processed_kompas2_uts.xlsx...")
df = pd.DataFrame(processed_paper)
df.to_excel('/content/sample_data/processed_kompas2_uts.xlsx', header=False, index=False)
print("Sukses.")

print("Menyimpan data ke corpus/kompas_words2_uts.xlsx...")
df = pd.DataFrame(words)
df.to_excel('/content/sample_data/kompas_words2_uts.xlsx', header=False, index=False)
print("Sukses.")

"""##  Mesin Pencari Berita"""

def perform_search(query_input, top_n=5):
    # preprocessing
    query = query_input.lower()
    remove_punctuation_map = dict((ord(char), None) for char in string.punctuation)
    query = query.translate(remove_punctuation_map)
    query = stopword.remove(query)
    query = [stemmer.stem(t) for t in query.split()]
    query_str = ' '.join(query)

    # TF-IDF
    vectorizer = TfidfVectorizer(use_idf=True)
    corpus = [query_str] + processed_paper
    paper_tfidf = vectorizer.fit_transform(corpus)
    query_vector = paper_tfidf[0]
    similarity_scores = cosine_similarity(paper_tfidf, query_vector)

    # hasil
    results = []
    for doc_idx in range(1, len(similarity_scores)):
        score = similarity_scores[doc_idx][0]
        if score > 0:
            i = doc_idx - 1
            results.append({
                'Document_ID': i,
                'Score': round(score, 4),
                'Judul': paper[i][1],
                'Waktu': paper[i][2],
                'Konten': paper[i][3]
            })

    results = sorted(results, key=lambda x: x['Score'], reverse=True)
    return results[:top_n]

# Interface UI

output = widgets.Output()

search_box = widgets.Text(
    placeholder='Ketik kata kunci pencarian...',
    description='Cari:',
    layout=widgets.Layout(width='500px'),
    style={'description_width': 'initial'}
)

search_button = widgets.Button(
    description='Cari',
    button_style='primary',
    layout=widgets.Layout(width='100px')
)

def on_search(b=None):
    with output:
        clear_output(wait=True)
        query = search_box.value.strip().lower()

        if not query:
            print("Masukkan kata kunci pencarian terlebih dahulu.")
            return

        print(f"Mencari berita yang relevan dengan: '{query}'")
        results = perform_search(query, top_n=50)

        if results:
            print(f"\nMenunjukkan {len(results)} hasil teratas:\n")
            display(pd.DataFrame(results))
        else:
            print("Tidak ada hasil yang ditemukan.")

search_button.on_click(on_search)
search_box.on_submit(on_search)

display(widgets.VBox([
    widgets.HBox([search_box, search_button]),
    output
]))